### ISSUE TITLE
Can’t get it to run 

### ISSUE THREAD

**Issue by Henoch09** [lacondeguy/Triangular_Arbitrage_Market_orders#2]
Hello, I was wondering how do you get this code to run. I have python already but when I try to run the code I get errors.

**Comment by lacondeguy** [comment]
Hello, what error do you have when running?

> Hello, I was wondering how do you get this code to run. I have python already but when I try to run the code I get errors.

**Comment by Henoch09** [comment]
I figure out the problem. It was my python. I got it to run successfully but I I’m having trouble figuring out the steps to test the triangular arbitrage. Usually it’s a step a- step c format for me to understand but I can’t figure out what to buy and sell to test it out.

**Comment by lacondeguy** [comment]
> I figure out the problem. It was my python. I got it to run successfully but I I’m having trouble figuring out the steps to test the triangular arbitrage. Usually it’s a step a- step c format for me to understand but I can’t figure out what to buy and sell to test it out.

My script is a fork, with additional functions. Read this for more details:
[github.com](https://github.com/Lakshmi-1212/TriangularArbitrageCryptos)
